### ISSUE TITLE
ctrl-[arrows] detected as ABCD

### ISSUE THREAD

**Issue by Shadlock0133** [jmacdonald/amp#131]
```yaml
keymap:
  insert:
    C: "buffer::change_rest_of_line"
    ctrl-right: "cursor::move_to_end_of_current_token"
```
Pressing ctrl-right will execute first line instead of expected second.
