### ISSUE TITLE
How to bind Caps Lock key to a command?

### ISSUE THREAD

**Issue by dar5hak** [jmacdonald/amp#144]
I am trying to bind my <kbd>Caps Lock</kbd> key to do things that <kbd>Esc</kbd> does.

Here's my custom keymap:

```yaml
keymap:
  insert:
    capslock: application::switch_to_normal_mode
```

But pressing the <kbd>Caps Lock</kbd> key in insert mode only triggers the usual behaviour of the key and doesn't switch to normal mode.

I tried with `caps_lock` but with same results.

How do I configure this correctly?
