### ISSUE TITLE
faster way to navigate lines

### ISSUE THREAD

**Issue by KiaraGrouwstra** [jmacdonald/amp#263]
**Is your feature request related to a problem? Please describe.**
After opening a file, I tend to move the cursor to the part of the file I'm interested in, which may well be down a bit.
I'd expect for e.g. PageDown to move the cursor down by a screen, but instead find it to not move the cursor at all.

**Describe the solution you'd like**
Have PageDown move the cursor, or have some other alternative to move the cursor by more than a line.

**Describe alternatives you've considered**
jjjjjjjjjjjjjjjjjjjjjjjjjjjjj

**Additional context**
n/a

**Comment by makouchyk** [comment]
You can try `f`. Don't need the cursor to move, when scrolling, as `f` will place it at the token anyway.

**Comment by KiaraGrouwstra** [comment]
i feel like for quickly navigating thru a large file without knowing much about its contents or line numbers, `f` isn't really much faster than `j` unfortunately :sweat:

**Comment by makouchyk** [comment]
I meant, you can use `f` __after__ you've already found a place to edit by scrolling with `m` and `,`.

**Comment by pbgc** [comment]
@KiaraGrouwstra as you can read in #158 this is considered a feature and not a problem. I really like how it works! you can browse up or down ... and comeback to where you were! if you don't want to comeback .. you use the f option to choose where exactly you want to stay.
If you some key binding to do the pageup pagedown and move the cursor .. you can define it!
https://amp.rs/docs/configuration/#key-bindings

Just define something like:
`
keymap:
  normal:
    ctrl-f:
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
            - "cursor::move_down"
    ctrl-e:
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
            - "cursor::move_up"
`

**Comment by KiaraGrouwstra** [comment]
@ppgc thanks. here's a version of `~/.config/amp/config.yml` i got to based on rebinding pageup/pagedown, tho the number of lines might depend on how many lines your screen can hold:
```yaml
keymap:
  normal:
    page_up:
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
    page_down:
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
```
