### ISSUE TITLE
Add support for different keyboard layouts.

### ISSUE THREAD

**Issue by simonsolnes** [jmacdonald/amp#35]
So that the N key will be mapped to J in colemak, and so on in different layouts.

**Comment by jmacdonald** [comment]
Amp [does support custom key mappings](https://amp.rs/docs/configuration/#key-bindings). That's not _exactly_ what you're after, but you can certainly mimic the behaviour.

If you'd like to be able to swap between different key layouts, you can just build the colemak layout and assign it to a different YAML key:

```yaml
... other config options

colemak_keymap:
  normal:
    n: cursor::move_down
    ... other key mappings
```

When you'd like to use the colemak keymap, just rename the `colemak_keymap` to `keymap` and Amp will use the specified values. 🙂
